# Take off and landig parameters
takeoff_height: 0.75
takeoff_rate: 0.5
landing_height: 0.005
landing_rate: 0.001

E_BB_width: 3.0 # emergency bounding box width limit
E_BB_height: 1.3 # emergency bounding box width limit

kalman_warmup: 10.0